CC = g++
CFLAGS = -std=c++11
DebugFlag=-g

test_bst: Binary_node.h Binary_tree.h Binary_search_tree.h utility.h
	$(CC) $(CFLAGS) -o test_bst test_bst.cpp $(DebugFlag)


clean:
	$(RM) test_bst *.o *~ *.gch
